# Generated by Django 3.0.2 on 2021-04-16 21:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('piazza', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walllike',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='wallpost',
            name='post_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
